version: '3'
services:
  ark-server:
    restart: unless-stopped
    build:
      context: .
    image: ark-server
    container_name: ark-server
    environment:
      - SESSION_NAME
      - ADMIN_PASSWORD
      - MAX_PLAYERS=20
      - QUERY_PORT=${QUERY_PORT:-27015}
      - GAME_PORT=${GAME_PORT:-7777}
      - MODS
      - CMD_ARGS
    ports:
      - "${QUERY_PORT:-27015}:${QUERY_PORT:-27015}/udp"
      - "${GAME_PORT:-7777}:${GAME_PORT:-7777}/udp"
    volumes:
      - "ark-data:/root/.steam/steam/steamapps/common/ARK Survival Ascended Dedicated Server"

volumes:
  ark-data:
    driver: local
    name: ark-data
